# Generated by Django 4.2.7 on 2023-11-20 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pegawai', '0006_remove_pegawaimodel_created_by_and_more'),
        ('arsip', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SirkulasiModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3038871d-1f7c-4b10-b599-ab51e8f35943'), editable=False, primary_key=True, serialize=False)),
                ('keperluan', models.TextField()),
                ('tanggal_pinjam', models.DateField()),
                ('tanggal_harus_kembali', models.DateField()),
                ('tanggal_kembali', models.DateField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sirkulasi_created', to=settings.AUTH_USER_MODEL)),
                ('nomor_arsip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arsip.arsipmodel')),
                ('peminjam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pegawai.pegawaimodel')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sirkulasi_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
