# Generated by Django 4.2.7 on 2023-12-01 02:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('397546dd-eef9-41f9-be7b-d70589bd5a97'), editable=False, primary_key=True, serialize=False),
        ),
    ]
