# Generated by Django 4.2.7 on 2023-12-26 03:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0002_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aed1eb8e-e181-4d95-86f3-07416d88bfe9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
