# Generated by Django 4.2.7 on 2024-01-01 09:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0003_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a405d16d-9327-432d-ab0f-91a62c9d5918'), editable=False, primary_key=True, serialize=False),
        ),
    ]
