# Generated by Django 4.2.7 on 2024-01-01 21:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0004_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bd7e2267-5c91-4d3e-ba6e-54edc4047a5d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
