# Generated by Django 4.2.7 on 2024-01-09 13:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0005_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c676de1f-d320-44ab-bc7e-f76f2ff9a77f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
