# Generated by Django 4.2.7 on 2024-01-17 22:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0007_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fa5ff090-8447-460a-8602-7856238fefee'), editable=False, primary_key=True, serialize=False),
        ),
    ]
