# Generated by Django 4.2.7 on 2024-02-06 07:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0009_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('935a0ac5-c931-4dfe-b1b0-87e4ca1db6c2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
