# Generated by Django 4.2.7 on 2024-02-17 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sirkulasi', '0010_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sirkulasi_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1b043ce1-1c9c-4588-9af2-7a4866a3fd2e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='updated_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sirkulasi_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
