# Generated by Django 4.2.7 on 2024-02-17 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0011_alter_sirkulasimodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('54401e02-a288-41a4-af90-bacbf06381e6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='tanggal_harus_kembali',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='tanggal_kembali',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='tanggal_pinjam',
            field=models.DateField(null=True),
        ),
    ]
