# Generated by Django 4.2.7 on 2024-03-05 06:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0012_alter_sirkulasimodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('91a8f660-fa3c-4630-aa06-71ee16eb913e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
