# Generated by Django 4.2.7 on 2024-03-05 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0013_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7f17b83d-c912-4427-9924-eb77e8ebf786'), editable=False, primary_key=True, serialize=False),
        ),
    ]
