# Generated by Django 4.2.7 on 2024-03-05 07:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0014_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('08d0886d-c629-42a4-8e47-acf46d9ef061'), editable=False, primary_key=True, serialize=False),
        ),
    ]
