# Generated by Django 4.2.7 on 2024-03-05 07:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0015_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('05f30d69-f722-4bae-b41b-a5ffb06be268'), editable=False, primary_key=True, serialize=False),
        ),
    ]
