# Generated by Django 4.2.7 on 2024-03-05 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0016_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8af67044-23da-4254-a0f2-66a08675bfaa'), editable=False, primary_key=True, serialize=False),
        ),
    ]
