# Generated by Django 4.2.7 on 2024-03-05 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0017_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0947252a-4014-4b15-a11c-7858ef9d043d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='sirkulasimodel',
            table='model_sirkulasi',
        ),
    ]
