# Generated by Django 4.2.7 on 2024-03-05 22:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0019_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('745d3eee-2e86-476b-b291-d9d626925678'), editable=False, primary_key=True, serialize=False),
        ),
    ]
