# Generated by Django 4.2.7 on 2024-03-06 01:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0020_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc8eedaa-09e4-490e-9a91-1058c3a69a28'), editable=False, primary_key=True, serialize=False),
        ),
    ]
