# Generated by Django 4.2.7 on 2024-03-06 01:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0021_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9ffddc0b-b369-4a02-a255-b5228db0d665'), editable=False, primary_key=True, serialize=False),
        ),
    ]
