# Generated by Django 4.2.7 on 2024-03-06 02:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0022_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6533dd2d-3b9c-4244-84b2-b9b773c77c6a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
