# Generated by Django 4.2.7 on 2024-03-06 02:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0023_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('17297841-17e2-4653-852c-f957e211fbfc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
