# Generated by Django 4.2.7 on 2024-03-26 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0024_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dbf30570-e518-4559-9e8c-0beb4f16733b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
