# Generated by Django 4.2.7 on 2024-04-03 09:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0025_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('74a87b4c-7625-4bb6-b653-7fa333ad1c62'), editable=False, primary_key=True, serialize=False),
        ),
    ]
