# Generated by Django 4.2.7 on 2024-04-03 12:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0026_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('45a8b741-55de-4e0f-b45d-f55c53bbfeac'), editable=False, primary_key=True, serialize=False),
        ),
    ]
