# Generated by Django 4.2.7 on 2024-04-03 12:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0027_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('78547907-05da-47b0-a9ba-d34feaf141ca'), editable=False, primary_key=True, serialize=False),
        ),
    ]
