# Generated by Django 4.2.7 on 2024-04-04 10:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0028_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('43835313-af47-42bf-a583-b4c47bb49333'), editable=False, primary_key=True, serialize=False),
        ),
    ]
