# Generated by Django 4.2.7 on 2024-04-06 07:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0030_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('19ee2cbd-68bc-490c-b74b-0439727b4e5e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
