# Generated by Django 4.2.7 on 2024-04-06 07:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0031_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('517c7720-9bce-4da2-ae6a-f5d2ca55b915'), editable=False, primary_key=True, serialize=False),
        ),
    ]
