# Generated by Django 4.2.7 on 2024-04-06 07:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0032_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9ef03bef-04cb-4b3f-9ca1-e1d8eac7b98a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
