# Generated by Django 4.2.7 on 2024-04-06 07:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0033_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ccb6b969-891e-4957-9eba-7fb23c947909'), editable=False, primary_key=True, serialize=False),
        ),
    ]
