# Generated by Django 4.2.7 on 2024-04-06 07:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0034_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b91bd855-01d5-4652-868a-3843c8968ff9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
