# Generated by Django 4.2.7 on 2024-04-06 07:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0035_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bbf4816f-3c8c-4d9a-ac86-ded7ab905b9a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
