# Generated by Django 4.2.7 on 2024-04-06 07:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0037_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3a4b316e-b33c-4dfd-bbfb-19b0a4778474'), editable=False, primary_key=True, serialize=False),
        ),
    ]
