# Generated by Django 4.2.7 on 2024-04-06 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0038_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5c9cda69-ebb6-4322-9b44-ca3a43d17ce3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
