# Generated by Django 4.2.7 on 2024-04-06 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0039_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4b67a1d1-dd02-46d1-a1ec-deda7323c830'), editable=False, primary_key=True, serialize=False),
        ),
    ]
