# Generated by Django 4.2.7 on 2024-04-06 07:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0040_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('84a3bcd3-9434-42c1-8b0c-8d02aed76260'), editable=False, primary_key=True, serialize=False),
        ),
    ]
