# Generated by Django 4.2.7 on 2024-04-13 13:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0041_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('01971587-d21b-4958-8166-c98b6e476a78'), editable=False, primary_key=True, serialize=False),
        ),
    ]
