# Generated by Django 4.2.7 on 2024-04-14 07:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0042_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0e0ca43b-9c76-4485-8848-f9b59596ff98'), editable=False, primary_key=True, serialize=False),
        ),
    ]
