# Generated by Django 4.2.7 on 2024-04-14 14:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0043_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bc1c5a94-d925-473b-9c62-6df1a389b863'), editable=False, primary_key=True, serialize=False),
        ),
    ]
