# Generated by Django 4.2.7 on 2024-04-18 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sirkulasi', '0044_alter_sirkulasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirkulasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('854775da-e4ae-41df-bfc6-5d6dfdcd6ad2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
