# Generated by Django 4.2.7 on 2023-11-17 07:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c50d72d6-fb40-4a9b-960f-ffda3c725e28'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'master_media',
            },
        ),
    ]
