# Generated by Django 4.2.7 on 2023-11-17 08:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('94ad20fd-024d-4732-827c-a074c14790ef'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='mediamodel',
            table='model_media',
        ),
    ]
