# Generated by Django 4.2.7 on 2023-11-18 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_mediamodel_id_alter_mediamodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('22f7fb40-7735-43c0-b7df-2606d75faffe'), editable=False, primary_key=True, serialize=False),
        ),
    ]
