# Generated by Django 4.2.7 on 2023-11-18 22:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_mediamodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('913be042-3e67-4615-bd26-e8777ade6d66'), editable=False, primary_key=True, serialize=False),
        ),
    ]
