# Generated by Django 4.2.7 on 2023-11-18 22:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_mediamodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fe6e7c8e-58f5-4cc9-9cfa-4be870059ade'), editable=False, primary_key=True, serialize=False),
        ),
    ]
