# Generated by Django 4.2.7 on 2023-11-18 23:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_alter_mediamodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9c88b18d-b674-4a2b-af1d-b578c4fb1983'), editable=False, primary_key=True, serialize=False),
        ),
    ]
