# Generated by Django 4.2.7 on 2023-11-19 01:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_alter_mediamodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1dcf8915-f49d-442c-a46a-393915bacdff'), editable=False, primary_key=True, serialize=False),
        ),
    ]
