# Generated by Django 4.2.7 on 2023-11-19 01:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_alter_mediamodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('88fc952e-bc6e-45aa-95da-50e9c58a803b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
