# Generated by Django 4.2.7 on 2023-11-19 02:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_alter_mediamodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0d07f982-2a7a-4cbd-9fac-56e456fae63e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
