# Generated by Django 4.2.7 on 2023-11-19 02:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_alter_mediamodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3a84df2f-fa2e-4092-953d-7f7c19b48e4f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
