# Generated by Django 4.2.7 on 2023-11-19 02:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_alter_mediamodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1a3cca98-cc7b-4c94-b8ea-4ea0fe136c38'), editable=False, primary_key=True, serialize=False),
        ),
    ]
