# Generated by Django 4.2.7 on 2023-11-19 02:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_alter_mediamodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c1ca8dcf-637a-4a6d-9605-70dbd2a51442'), editable=False, primary_key=True, serialize=False),
        ),
    ]
