# Generated by Django 4.2.7 on 2023-11-19 02:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0013_alter_mediamodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('316b6186-55f3-4b8c-a2d6-ab7a77e1a71f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
