# Generated by Django 4.2.7 on 2023-11-19 02:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0014_alter_mediamodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4a98ff1-dfe9-42a6-90d5-f87a829cbe89'), editable=False, primary_key=True, serialize=False),
        ),
    ]
