# Generated by Django 4.2.7 on 2023-11-19 02:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0015_alter_mediamodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('65c763ea-29a3-41c9-b150-ebfadbfe465d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
