# Generated by Django 4.2.7 on 2023-11-19 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0016_alter_mediamodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f0b2cd8c-8deb-4477-ab9c-68dcc1da1737'), editable=False, primary_key=True, serialize=False),
        ),
    ]
