# Generated by Django 4.2.7 on 2023-11-19 07:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0017_alter_mediamodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('80e85d4a-3a01-4ecc-96ce-58b0ea22f20b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
