# Generated by Django 4.2.7 on 2023-11-20 02:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0019_alter_mediamodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f480de73-32da-476f-89ad-7069ba88ae5c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
