# Generated by Django 4.2.7 on 2023-11-20 05:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0020_alter_mediamodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c35b39c7-31d3-46f5-a350-266dc07726bc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
