# Generated by Django 4.2.7 on 2023-11-20 06:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0021_alter_mediamodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('639cf665-0ff8-4018-b3b3-442a833e580a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
