# Generated by Django 4.2.7 on 2023-11-20 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0022_alter_mediamodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a664c183-cbe7-4fe9-a0a3-f31defac4dc2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
