# Generated by Django 4.2.7 on 2024-03-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0024_alter_mediamodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
