# Generated by Django 4.2.7 on 2023-11-19 01:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unit_kerja', '0003_subunitkerjamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PegawaiModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identitas', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'master_member',
            },
        ),
        migrations.CreateModel(
            name='PegawaiUnitKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegawai.pegawaimodel')),
                ('sub_unit_kerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit_kerja.subunitkerjamodel')),
                ('unit_kerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit_kerja.unitkerjamodel')),
            ],
            options={
                'db_table': 'pegawai_unit_kerja',
            },
        ),
        migrations.AddField(
            model_name='pegawaimodel',
            name='sub_unit_kerja',
            field=models.ManyToManyField(through='pegawai.PegawaiUnitKerja', to='unit_kerja.subunitkerjamodel'),
        ),
        migrations.AddField(
            model_name='pegawaimodel',
            name='unit_kerja',
            field=models.ManyToManyField(through='pegawai.PegawaiUnitKerja', to='unit_kerja.unitkerjamodel'),
        ),
    ]
