# Generated by Django 4.2.7 on 2023-11-19 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_kerja', '0003_subunitkerjamodel'),
        ('pegawai', '0002_remove_pegawaimodel_sub_unit_kerja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawaimodel',
            name='sub_unit_kerja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unit_kerja.subunitkerjamodel'),
        ),
    ]
