# Generated by Django 4.2.7 on 2023-11-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0004_pegawaistatusmodel_pegawaimodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawaistatusmodel',
            name='keterangan',
            field=models.CharField(default='D', max_length=150, null=True),
        ),
    ]
