# Generated by Django 4.2.7 on 2023-11-20 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pegawai', '0005_pegawaistatusmodel_keterangan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pegawaimodel',
            name='created_by',
        ),
        migrations.AddField(
            model_name='pegawaimodel',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
