# Generated by Django 4.2.7 on 2023-12-01 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pegawai', '0006_remove_pegawaimodel_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawaimodel',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
