# Generated by Django 4.2.7 on 2023-12-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0007_alter_pegawaimodel_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawaistatusmodel',
            name='keterangan',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
