# Generated by Django 4.2.7 on 2024-01-01 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_kerja', '0005_unitkerjamodel_arsip'),
        ('pegawai', '0008_alter_pegawaistatusmodel_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawaimodel',
            name='unit_kerja',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='unit_kerja.unitkerjamodel'),
        ),
    ]
