# Generated by Django 4.2.7 on 2024-03-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0010_alter_pegawaimodel_user_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pegawaimodel',
            table='model_pegawai',
        ),
    ]
