# Generated by Django 4.2.7 on 2024-03-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0011_alter_pegawaimodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pegawaistatusmodel',
            table='model_status_pegawai',
        ),
    ]
