# Generated by Django 4.2.7 on 2024-03-06 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pangkat_golongan', '0001_initial'),
        ('pegawai', '0013_alter_pegawaimodel_id_alter_pegawaistatusmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawaimodel',
            name='jabatan',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pegawaimodel',
            name='pangkat_golongan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pangkat_golongan.pangkatgolonganmodel'),
        ),
    ]
