# Generated by Django 4.2.7 on 2024-03-26 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pegawai', '0014_pegawaimodel_jabatan_pegawaimodel_pangkat_golongan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawaimodel',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
