# Generated by Django 4.2.7 on 2024-03-05 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dokumenmodel',
            table='model_dokumen',
        ),
    ]
