# Generated by Django 4.2.7 on 2024-03-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PangkatGolonganModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pangkat', models.CharField(max_length=100)),
                ('golongan', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'model_pangkat_golongan',
            },
        ),
    ]
