# Generated by Django 4.2.7 on 2023-11-20 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0022_alter_mediamodel_id'),
        ('unit_kerja', '0003_subunitkerjamodel'),
        ('lokasi', '0023_alter_lokasimodel_id_alter_tempatmodel_id'),
        ('klasifikasi', '0011_klasifikasimodel_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArsipModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('no_arsip', models.CharField(max_length=200)),
                ('tanggal_dokumen', models.DateField()),
                ('uraian', models.TextField()),
                ('keterangan', models.CharField(max_length=100)),
                ('nomor_box', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arsip_created', to=settings.AUTH_USER_MODEL)),
                ('kode_klasifikasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klasifikasi.klasifikasimodel')),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lokasi.lokasimodel')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.mediamodel')),
                ('pencipta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arsip_pencipta', to='unit_kerja.unitkerjamodel')),
                ('pengelola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arsip_pengelola', to='unit_kerja.unitkerjamodel')),
                ('tempat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lokasi.tempatmodel')),
                ('updated_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arsip_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
