# Generated by Django 4.2.7 on 2023-12-01 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arsipmodel',
            old_name='updated_at',
            new_name='updated_by',
        ),
    ]
