# Generated by Django 4.2.7 on 2023-12-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0002_rename_updated_at_arsipmodel_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arsipmodel',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
