# Generated by Django 4.2.7 on 2024-03-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0004_arsipmodel_jenis_dokumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='arsipmodel',
            name='asal_surat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='arsipmodel',
            name='tujuan_surat',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
