# Generated by Django 4.2.7 on 2024-04-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0005_arsipmodel_asal_surat_arsipmodel_tujuan_surat'),
    ]

    operations = [
        migrations.AddField(
            model_name='arsipmodel',
            name='tanggal_terima',
            field=models.DateField(default=None, null=True),
        ),
    ]
