# Generated by Django 4.2.7 on 2024-04-04 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0026_alter_tempatmodel_table'),
        ('arsip', '0008_alter_arsipmodel_tanggal_terima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arsipmodel',
            name='asal_surat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='arsipmodel',
            name='lokasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lokasi.lokasimodel'),
        ),
        migrations.AlterField(
            model_name='arsipmodel',
            name='nomor_box',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='arsipmodel',
            name='tempat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lokasi.tempatmodel'),
        ),
        migrations.AlterField(
            model_name='arsipmodel',
            name='tujuan_surat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
