# Generated by Django 4.2.7 on 2024-04-06 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0027_boxmodel'),
        ('arsip', '0009_alter_arsipmodel_asal_surat_alter_arsipmodel_lokasi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arsipmodel',
            name='nomor_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lokasi.boxmodel'),
        ),
    ]
