# Generated by Django 4.2.7 on 2024-04-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0013_arsipmodel_nomor_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arsipmodel',
            name='nomor_box',
        ),
    ]
