# Generated by Django 4.2.7 on 2024-04-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0025_alter_mediamodel_id'),
        ('klasifikasi', '0014_klasifikasimodel_sub_unit_kerja_and_more'),
        ('arsip', '0015_arsipmodel_nomor_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arsipmodel',
            name='kode_klasifikasi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='klasifikasi.klasifikasimodel'),
        ),
        migrations.AlterField(
            model_name='arsipmodel',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.mediamodel'),
        ),
    ]
