# Generated by Django 4.2.7 on 2024-04-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0016_alter_arsipmodel_kode_klasifikasi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arsipmodel',
            name='tanggal_terima',
            field=models.DateField(blank=True, null=True),
        ),
    ]
