# Generated by Django 4.2.7 on 2024-04-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0017_alter_arsipmodel_tanggal_terima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arsipmodel',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
