# Generated by Django 4.2.7 on 2024-04-18 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klasifikasi', '0014_klasifikasimodel_sub_unit_kerja_and_more'),
        ('arsip', '0018_alter_arsipmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arsipmodel',
            name='kode_klasifikasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='klasifikasi.klasifikasimodel'),
        ),
    ]
