# Generated by Django 4.2.7 on 2023-11-17 07:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LokasiModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('973b3ddc-c1d8-4b66-bddf-4bc64b3a894d'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'master_lokasi',
            },
        ),
    ]
