# Generated by Django 4.2.7 on 2023-11-17 07:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1dc2babf-9317-4916-baff-aa8da8aa30ab'), editable=False, primary_key=True, serialize=False),
        ),
    ]
