# Generated by Django 4.2.7 on 2023-11-17 08:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0002_alter_lokasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('488d2514-6ea2-4d03-a494-cc5bc6f2cc0f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='lokasimodel',
            table='model_lokasi',
        ),
    ]
