# Generated by Django 4.2.7 on 2023-11-18 22:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0004_alter_lokasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bb0c98ae-ee0f-4f03-b4af-ed55c98968b8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
