# Generated by Django 4.2.7 on 2023-11-18 22:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0005_alter_lokasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10f71de3-aaee-40b1-a12b-9082067d2fa1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
