# Generated by Django 4.2.7 on 2023-11-18 23:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0006_alter_lokasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cee7ea61-c5b9-4f96-9ab6-7e46f2d6a3e2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
