# Generated by Django 4.2.7 on 2023-11-19 01:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0007_alter_lokasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d5cabebe-6b9d-4376-b04a-e64bb369d6a0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
