# Generated by Django 4.2.7 on 2023-11-19 01:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0008_alter_lokasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1537ae05-dd35-4352-aecd-b04d44a31c18'), editable=False, primary_key=True, serialize=False),
        ),
    ]
