# Generated by Django 4.2.7 on 2023-11-19 02:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0009_alter_lokasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c81eace0-81d2-4073-9b07-aea18fdc3a33'), editable=False, primary_key=True, serialize=False),
        ),
    ]
