# Generated by Django 4.2.7 on 2023-11-19 02:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0010_alter_lokasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('66a7af28-cb13-44eb-afed-4c9d41d71dbd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
