# Generated by Django 4.2.7 on 2023-11-19 02:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0011_alter_lokasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f5e8ba3-245c-4b3e-a46e-4f45487d3af6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
