# Generated by Django 4.2.7 on 2023-11-19 02:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0012_alter_lokasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fca7fc4b-5296-4f5a-aad4-e300858d363f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
