# Generated by Django 4.2.7 on 2023-11-19 02:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0013_alter_lokasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d4bf7c4b-3f89-4163-bc43-ebd6039b9076'), editable=False, primary_key=True, serialize=False),
        ),
    ]
