# Generated by Django 4.2.7 on 2023-11-19 02:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0015_alter_lokasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9f3218ea-aee9-4d69-9839-de307a86c677'), editable=False, primary_key=True, serialize=False),
        ),
    ]
