# Generated by Django 4.2.7 on 2023-11-19 02:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0016_alter_lokasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('25aa5223-fd0a-4c78-a001-96d21ff13d40'), editable=False, primary_key=True, serialize=False),
        ),
    ]
