# Generated by Django 4.2.7 on 2023-11-19 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0017_alter_lokasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('73e3497f-d94d-472e-a3d2-249e049805f8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
