# Generated by Django 4.2.7 on 2023-11-19 07:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0018_alter_lokasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c49834f1-e0b7-434e-b3c5-235d47006c76'), editable=False, primary_key=True, serialize=False),
        ),
    ]
