# Generated by Django 4.2.7 on 2023-11-19 07:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0019_alter_lokasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9f3b0828-9348-4b5e-bdd1-90b094331af8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
