# Generated by Django 4.2.7 on 2023-11-20 02:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0020_alter_lokasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('18d808ab-490b-4b23-a649-222a5210d860'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TempatModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('deaa28bf-db09-4c52-9998-7c05ec8e656f'), editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200)),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lokasi.lokasimodel')),
            ],
        ),
    ]
