# Generated by Django 4.2.7 on 2023-11-20 05:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0021_alter_lokasimodel_id_tempatmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b5a72b9a-57ab-47fc-897a-50f6c9ad3112'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tempatmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9fa1159d-d607-4bbd-8ee2-04543621e78a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
