# Generated by Django 4.2.7 on 2023-11-20 06:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0022_alter_lokasimodel_id_alter_tempatmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5e91e079-b8d9-43c1-bb69-64a4f96d9182'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tempatmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('50ec30ae-1ac1-4e30-940b-558ff0a50782'), editable=False, primary_key=True, serialize=False),
        ),
    ]
