# Generated by Django 4.2.7 on 2023-11-20 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0023_alter_lokasimodel_id_alter_tempatmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c402be5e-a968-4e13-99c3-1b0947915289'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tempatmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b414aa8-befc-4b5e-9727-3949b20c4e64'), editable=False, primary_key=True, serialize=False),
        ),
    ]
