# Generated by Django 4.2.7 on 2024-03-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0025_alter_lokasimodel_id_alter_tempatmodel_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tempatmodel',
            table='model_tempat',
        ),
    ]
