# Generated by Django 4.2.7 on 2023-11-05 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_kerja', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unitkerjamodel',
            table='model_unit_kerja',
        ),
    ]
