# Generated by Django 4.2.7 on 2023-11-17 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unit_kerja', '0002_alter_unitkerjamodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubUnitKerjaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unit_kerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit_kerja.unitkerjamodel')),
            ],
            options={
                'db_table': 'model_sub_unit_kerja',
            },
        ),
    ]
