# Generated by Django 4.2.7 on 2023-12-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_kerja', '0004_alter_subunitkerjamodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitkerjamodel',
            name='arsip',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
