# Generated by Django 4.2.7 on 2023-11-08 22:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KlasifikasiModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('4856931e-a620-4b04-8787-2a643f122221'), editable=False, primary_key=True, serialize=False)),
                ('kode_klasifikasi', models.CharField(max_length=50)),
                ('nama', models.TextField()),
            ],
        ),
    ]
