# Generated by Django 4.2.7 on 2023-11-08 22:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klasifikasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klasifikasimodel',
            name='kategory_klasifikasi',
            field=models.CharField(choices=[('FASILITATIF', 'Arsip Fasilitatif'), ('SUBSTANTIF', 'Arsip Subtantif')], default='FASILITATIF', max_length=20),
        ),
        migrations.AlterField(
            model_name='klasifikasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('48655743-76b2-4fc5-ab68-a47106fa75f4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='klasifikasimodel',
            table='model_klasifikasi',
        ),
    ]
