# Generated by Django 4.2.7 on 2023-11-17 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klasifikasi', '0002_klasifikasimodel_kategory_klasifikasi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klasifikasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b564a590-92df-41c6-8884-b9f23877afba'), editable=False, primary_key=True, serialize=False),
        ),
    ]
