# Generated by Django 4.2.7 on 2023-11-17 07:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klasifikasi', '0003_alter_klasifikasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klasifikasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b0ff3f5b-75da-4bf7-81e4-88574dfad9e5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
