# Generated by Django 4.2.7 on 2023-11-17 07:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klasifikasi', '0004_alter_klasifikasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klasifikasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e0b5289d-44b9-48a3-a664-d309119cb8da'), editable=False, primary_key=True, serialize=False),
        ),
    ]
