# Generated by Django 4.2.7 on 2023-11-17 07:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klasifikasi', '0005_alter_klasifikasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klasifikasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7076d1b7-10ec-4cd1-8507-4d78de53a3ec'), editable=False, primary_key=True, serialize=False),
        ),
    ]
