# Generated by Django 4.2.7 on 2023-11-17 08:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klasifikasi', '0006_alter_klasifikasimodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klasifikasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b0d33f3a-8112-4c79-8152-f1d06b598c8f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
