# Generated by Django 4.2.7 on 2023-11-18 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klasifikasi', '0007_alter_klasifikasimodel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klasifikasimodel',
            old_name='kategory_klasifikasi',
            new_name='kategory_arsip',
        ),
        migrations.RenameField(
            model_name='klasifikasimodel',
            old_name='nama',
            new_name='keterangan',
        ),
        migrations.AddField(
            model_name='klasifikasimodel',
            name='jenis_arsip',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='klasifikasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f200d986-a654-48f5-8163-01c4dfedfd2d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
