# Generated by Django 4.2.7 on 2023-11-18 22:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klasifikasi', '0008_rename_kategory_klasifikasi_klasifikasimodel_kategory_arsip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klasifikasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8bae939d-e165-4006-896c-d7468fdd7994'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='klasifikasimodel',
            name='keterangan',
            field=models.TextField(null=True),
        ),
    ]
