# Generated by Django 4.2.7 on 2023-11-18 22:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klasifikasi', '0009_alter_klasifikasimodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klasifikasimodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cb13baee-01bc-4788-b5dc-792bfa3be484'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='klasifikasimodel',
            name='keterangan',
            field=models.TextField(default=''),
        ),
    ]
