# Generated by Django 4.2.7 on 2023-11-18 23:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('klasifikasi', '0010_alter_klasifikasimodel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klasifikasimodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='klasifikasimodel',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='klasifikasimodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='klasifikasimodel',
            name='kategory_arsip',
            field=models.CharField(choices=[('FASILITATIF', 'Arsip Fasilitatif'), ('SUBSTANTIF', 'Arsip Subtantif')], default='SUBSTANTIF', max_length=20),
        ),
        migrations.AlterField(
            model_name='klasifikasimodel',
            name='keterangan',
            field=models.TextField(null=True),
        ),
    ]
