# Generated by Django 4.2.7 on 2024-01-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klasifikasi', '0011_klasifikasimodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klasifikasimodel',
            name='nasib_akhir',
            field=models.CharField(choices=[('Musnah', 'Musnah'), ('Permanen', 'Permanen'), ('Masuk berkas perseorangan', 'Masuk berkas perseorangan')], default='Musnah', max_length=100),
        ),
        migrations.AddField(
            model_name='klasifikasimodel',
            name='waktu_aktif',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='klasifikasimodel',
            name='waktu_inaktif',
            field=models.IntegerField(null=True),
        ),
    ]
