# Generated by Django 4.2.7 on 2024-03-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klasifikasi', '0012_klasifikasimodel_nasib_akhir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klasifikasimodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
